name: 'Shifter Action'
description: 'Github Action to replace strings in files or directories'
branding:
  icon: aperture
  color: blue
inputs:
  patterns:  
    description: 'Patterns to replace'
    required: true
    default: ""
  delimiter:  
    description: 'Delimiter'
    required: true
    default: ""
  equal_sign:  
    description: 'Equal Sign'
    required: true
    default: "="
runs:
  using: 'node20'
  main: 'index.js'